/// Autogenerated by Targets - Edit tests.json instead of this file
import 'helpers.dart';
final String name = "Grandma's Spy App";
final String owner = "mvhs";
final String id = "spy-app";
final List<String> files = ["WordFilter.java","SpyApp.java"];
List<Target> getTargets() {
    var targets = [];
    targets.addAll(IOTarget.makeMultiJava("WordFilterTest", [new InputOutput.withArgs("getFourLetterWords", "getFourLetterWords", "passed", 1), new InputOutput.withArgs("findFour", "findFour", "passed", 3), new InputOutput.withArgs("replaceFour", "replaceFour", "passed", 3), new InputOutput.withArgs("getLog", "getLog", "passed", 1), new InputOutput.withArgs("printFilteredText", "printFilteredText", "passed", 2), new InputOutput.withArgs("Bonus Challenge", "challenge", "", -1), ]));
    return targets;
}
